% After you have DRAIN_LID_database.mat
load('results.mat', 'Metrics', ...
     'Peff_set_mm', 'tp_set_min', 'Ld_set_m', 'area_ratio_set');

% Convert to a simpler table-like struct for JS
soilNames = unique({Metrics.soilName}, 'stable');

allData = struct();
allData.soils = soilNames;
allData.Peff_mm = Peff_set_mm;
allData.tp_min  = tp_set_min;
allData.Ld_m    = Ld_set_m;
allData.area_ratio = area_ratio_set;

% For convenience, we flatten Metrics into arrays
n = numel(Metrics);
allData.metrics = struct( ...
    'soilName',      {Metrics.soilName}, ...
    'Aup_m2',        num2cell([Metrics.Aup_m2]), ...
    'ATC_m2',        num2cell([Metrics.ATC_m2]), ...
    'area_ratio',    num2cell([Metrics.area_ratio]), ...
    'Ld_m',          num2cell([Metrics.Ld_m]), ...
    'Peff_catch_mm', num2cell([Metrics.Peff_catch_mm]), ...
    'Peff_eq_mm',    num2cell([Metrics.Peff_eq_mm]), ...
    'tp_min',        num2cell([Metrics.tp_min]), ...
    'Qp_in_m3s',     num2cell([Metrics.Qp_in_m3s]), ...
    'Qp_out_m3s',    num2cell([Metrics.Qp_out_m3s]), ...
    'eta_p_pct',     num2cell([Metrics.eta_p_pct]), ...
    'Delta_tp_min',  num2cell([Metrics.Delta_tp_min]), ...
    'DetTime_min',   num2cell([Metrics.DetTime_min]), ...
    'DeltaV_m3',     num2cell([Metrics.DeltaV_m3]), ...
    'max_ponding',   num2cell([Metrics.max_ponding]) );

% Save as JSON
jsonStr = jsonencode(allData);
fid = fopen('drain_lid_database.json','w');
fwrite(fid, jsonStr, 'char');
fclose(fid);